name: "build"
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-android:
    name: "Build Android App"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Java 17 Environment
        uses: actions/setup-java@v4
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build Android Application
        run: flutter build apk
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk-build
          path: build/app/outputs/apk/release
          if-no-files-found: error
    
  build-windows:
    name: "Build Windows App"
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build Windows Application
        run: flutter build windows
      - name: Create Windows Application Installer
        run: iscc "windowsApplicationInstallerSetup.iss"
        working-directory: .
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: exe-build
          path: windowsTemp/BusAppInstall.exe
          if-no-files-found: error

  build-linux:
    name: "Build linux app"
    runs-on: ubuntu-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: |
          sudo apt-get update -y
          sudo apt-get install -y ninja-build libgtk-3-dev
      - run: flutter build linux

  build-macos:
    name: "Build macOS app"
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build macos

  build-ios:
    name: "Build ios app"
    runs-on: macos-latest
    steps:
      - name: Clone repository
        uses: actions/checkout@v4
      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable
      - run: flutter build ios --release --no-codesign
      - name: Archive Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ios-build
          path: build/ios/iphoneos
          if-no-files-found: error

      # build/ios/iphoneos/Runner.app
