name: "build"
on:
  push:
    branches:
      - main
    tags-ignore:
      - '*'
  pull_request:

jobs:
  build-android:
    name: "Build Android App"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Java 17 Environment
        uses: actions/setup-java@v3
        with:
          distribution: "temurin"
          java-version: "17"
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build Android Application
        run: flutter build apk
      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: apk-build
          path: build/app/outputs/apk/release
          if-no-files-found: error
    
  build-windows:
    name: "Build Windows App"
    runs-on: windows-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3
      - name: Setup Flutter Environment
        uses: subosito/flutter-action@v2
        with:
          channel: "stable"
      - name: Build Windows Application
        run: flutter build windows
      - name: Create Windows Application Installer
        run: iscc "windowsApplicationInstallerSetup.iss"
        working-directory: .
      - name: Archive Artifact
        uses: actions/upload-artifact@v3
        with:
          name: exe-build
          path: windowsTemp/WindowsApplication.exe
          if-no-files-found: error
